## Multivariable linear regression

### Recap

* Hypothesis
$$ H(x) = Wx + b$$

* Cost Function
$$ \text{cost}(W,b) = { 1 \over m} \sum_{i=1}^m (H(x^{(i)})-y^{(i)})^2 $$

* Gradient descent algorithm


### Predicting exam score: regression using one input (x)

| x (Hours)  | y (score) |
|    :---:   |   :---:   |
|    10      |     90    |
|     9      |     80    |
|     3      |     50    |
|     2      |     60    |
|     11     |     40    |

### Predicting exam score: regression using three inputs (x1, x2, x3)

| x1 (quiz 1) | x2 (quiz 2)| x3 (midterm 1)  | Y (final) |
|    :---:   |   :---:   |    :---:   |   :---:   |
|    73      |     80    | 75 | 152 |
|    93      |     88    | 93  | 185  |
|    89      |     91    |  90  | 180  |
|    96      |     98    |   100 |  196  |
|    73     |     66    |   70   | 142   |


####  Hypothesis

$$ H(x) = Wx + b$$
 
$$ H(x_1,x_2, x_3) = w_1x_1 + w_2x_2 + w_3x_3 + b$$

#### Cost function

$$ \text{cost}(W,b) = { 1 \over m} \sum_{i=1}^m (H(x_1^{(i)}, x_2^{(i)},x_3^{(i)})-y^{(i)})^2 $$

####  Multi-variable
 
$$ H(x_1,x_2, x_3) = w_1x_1 + w_2x_2 + \cdots + w_nx_n + b$$

#### Multi-variable Hypothesis using Matrix

$$  w_1x_1 + w_2x_2 + \cdots + w_nx_n  $$

$$ [ x_1  x_2  x_3 ] \cdot \begin{bmatrix} w_1 \\ w_2 \\ w_3 \end{bmatrix} = x_1w_1 + x_2w_2 + x_3w_3 $$

$$ H(X) = XW $$


For many instances ...
$$ \begin{bmatrix} 
x_{11}  & x_{12} & x_{13} \\
x_{21}  & x_{22} & x_{33} \\
x_{31}  & x_{32} & x_{33} \\
x_{41}  & x_{42} & x_{43} \\
x_{51}  & x_{52} & x_{53}
\end{bmatrix} \cdot 
\begin{bmatrix} w_1 \\ w_2 \\ w_3  \end{bmatrix}
= 
 \begin{bmatrix} 
 x_{11}w_1 + x_{12}w_2 + x_{13}w_3 \\
 x_{21}w_1 + x_{22}w_2 + x_{33}w_3 \\
 x_{31}w_1 + x_{32}w_2 + x_{33}w_3 \\
 x_{41}w_1 + x_{42}w_2 + x_{43}w_3 \\
 x_{51}w_1 + x_{52}w_2 + x_{53}w_3 
  \end{bmatrix}
  $$
  
 [n x 3] * [3 x 1] = [n x 1] 

### XW vs XW

* Lecture(i.e. theory)
$$ H(x) = Wx + b $$
* Implementation (i.e. Tensorflow)
$$ H(X) = X W $$

## Lab 4-1

| $x_1$ |  $x_2$|  $x_3$  | Y  |
|    :---:   |   :---:   |    :---:   |   :---:   |
|    73      |     80    | 75 | 152 |
|    93      |     88    | 93  | 185  |
|    89      |     91    |  90  | 180  |
|    96      |     98    |   100 |  196  |
|    73     |     66    |   70   | 142   |

In [36]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict={x1: x1_data, x2:x2_data, x3: x3_data, Y: y_data})
    if step % 400 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

0 Cost:  197999.1 
Prediction: 
 [-251.6882  -283.95578 -289.39877 -316.06317 -210.94164]
400 Cost:  32.75611 
Prediction: 
 [144.0221  189.90645 178.41617 193.28487 150.1351 ]
800 Cost:  26.472574 
Prediction: 
 [144.85384 189.33496 178.66939 193.48056 149.37463]
1200 Cost:  21.412365 
Prediction: 
 [145.59961 188.82245 178.8963  193.65706 148.69165]
1600 Cost:  17.33698 
Prediction: 
 [146.26826 188.36285 179.09961 193.81636 148.07819]
2000 Cost:  14.054525 
Prediction: 
 [146.86769 187.95065 179.2817  193.96017 147.5271 ]


Simplify the code using Matrix

In [37]:
x_data = [[73., 80., 75.], 
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict={X: x_data, Y: y_data})
    if step % 400 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

0 Cost:  133870.17 
Prediction: 
 [[-168.18774]
 [-208.99846]
 [-202.53593]
 [-220.76196]
 [-160.60805]]
400 Cost:  10.768486 
Prediction: 
 [[155.9149 ]
 [181.54868]
 [181.75726]
 [197.77518]
 [137.48723]]
800 Cost:  8.720679 
Prediction: 
 [[155.44022]
 [181.87485]
 [181.61276]
 [197.66328]
 [137.9215 ]]
1200 Cost:  7.0715227 
Prediction: 
 [[155.0146 ]
 [182.16737]
 [181.48328]
 [197.56235]
 [138.31151]]
1600 Cost:  5.74327 
Prediction: 
 [[154.63301]
 [182.4297 ]
 [181.3673 ]
 [197.47124]
 [138.66187]]
2000 Cost:  4.673442 
Prediction: 
 [[154.29092]
 [182.66492]
 [181.26337]
 [197.38892]
 [138.97658]]


## Lab. 4-2 : Loading data from file

text file as ./data/data-01-test-score.csv

In [15]:
# EXAM1,EXAM2,EXAM3,FINAL
73,80,75,152
93,88,93,185
89,91,90,180
96,98,100,196
73,66,70,142
53,46,55,101

(53, 46, 55, 101)

In [38]:
import numpy as np

xy = np.loadtxt('data/data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


In [39]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict={X: x_data, Y: y_data})
    if step % 400 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)

0 Cost:  7713.289 
Prediction: 
 [[72.59785 ]
 [82.759285]
 [83.746605]
 [92.50187 ]
 [60.949173]
 [46.44678 ]]
400 Cost:  8.877568 
Prediction: 
 [[154.61263 ]
 [181.99835 ]
 [181.18567 ]
 [198.6222  ]
 [136.799   ]
 [102.448296]]
800 Cost:  7.9793277 
Prediction: 
 [[154.29158]
 [182.16882]
 [181.06693]
 [198.4927 ]
 [137.06749]
 [102.71099]]
1200 Cost:  7.25989 
Prediction: 
 [[154.01105]
 [182.31921]
 [180.96436]
 [198.37482]
 [137.3085 ]
 [102.93611]]
1600 Cost:  6.6783633 
Prediction: 
 [[153.76598 ]
 [182.45206 ]
 [180.87593 ]
 [198.2672  ]
 [137.5254  ]
 [103.128395]]
2000 Cost:  6.203535 
Prediction: 
 [[153.55196 ]
 [182.56949 ]
 [180.79988 ]
 [198.16861 ]
 [137.72107 ]
 [103.292015]]


In [40]:
#
print("Your score will be ", sess.run(hypothesis, feed_dict={X:[[100, 70, 101]]}))

Your score will be  [[179.4285]]


In [41]:
print("Your score will be ", sess.run(hypothesis, 
                                      feed_dict={X:[[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[183.47055]
 [176.3312 ]]


### Queue Runners
<img src="https://t1.daumcdn.net/cfile/tistory/223B9B4958F7733C01">

<img src="https://t1.daumcdn.net/cfile/tistory/210E514958F7733B3C">

tf.train.batch

In [ ]:
import tensorflow as tf

filename_queue = tf.train.string_input_producer(
    ['data/data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
   
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()

sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                  feed_dict={X: x_batch, Y: y_batch})
    if step % 400 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction: \n", hy_val)
    
coord.request_stop()
coord.join(thresds)

In [ ]:
import tensorflow as tf
filename_queue = tf.train.string_input_producer(\
        ['data/data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the decoded result.
record_defaults = [[0.], [0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults = record_defaults)

#collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

#placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

#Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a sesseion.
sess = tf.Session()

# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train],
        feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val,
                     "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)